### PR TITLE
Update read_gtf.py

### PR DESCRIPTION
**Pull request by y9c**
fix palars error

### CODE REVIEW

**Comment by y9c** [comment]
https://github.com/openvax/gtfparse/pull/34

**Comment by y9c** [comment]
https://github.com/openvax/gtfparse/pull/35

**Comment by hsn-ylmz** [comment]
polars also change toggle_string_cache(True) to enable_string_cache(True). Can you please change it and update the conda version?

**Comment by kmlhpk** [comment]
thanks for this @y9c, I applied this patch by hand (as well as the string cache thing that @hsn-ylmz mentioned) and it fixed my issues.

**Comment by y9c** [comment]
Hi @hsn-ylmz. Thank you for your suggestion. I have updated accordingly. Could you help review and merge this patch?

**Review by kmlhpk — APPROVED** [review]
applied these diffs by hand and they fixed my issues, can recommend

**Comment by jdcla** [comment]
@iskandr gtfparse has been broken for polars>v.016.x Polars is currently at v0.19.19. Any change of these patches being implemented soon?

**Comment by y9c** [comment]
There is also some bugs in the current release. For example, if there is a ";" in the attribute of the record, gtfparse can not parse the file in the correct way.

**Comment by iskandr** [comment]
Sorry I was missing these notifications and leaving this broken, I'll take a look today.

**Comment by iskandr** [comment]
Fixed by https://github.com/openvax/gtfparse/pull/42 -- sorry I left this hanging for so long.

**Pull request closed without merging**
